framework:
    messenger:
        transports:
            grabber:
                 dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            App\Message\GrabResourceMessage: grabber
#            'App\Message\GrabberMessageInterface': grabber